version: '3.4'

services:
  webapp_gaia:
    build:
      context: ./web_app
      dockerfile: Dockerfile  
    ports:
      - "${WEB_PORT}:8050"
    volumes:
      - ./web_app:/code
    environment:
      - DEFAULT_LONGITUDE
      - DEFAULT_LATITUDE
      - WEB_DEBUG
    depends_on:
      - dbapp_gaia
    networks:
      - targets_list_network_gaia
    command: ["python3", "-u", "main.py"]

  dbapp_gaia:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/targets_database:/code
    links:
      - "db_gaia:db_gaia"
    ports:
      - "${DATABASE_PORT}:8000"
    depends_on:
      - db_gaia
    environment:
      - DATABASE_DEBUG
      - DATABASE_SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - targets_list_network_gaia
    command: ["python3.8", "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]

  db_gaia:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata_gaia:/var/lib/postgresql/data 
    networks:
      - targets_list_network_gaia

volumes:
  pgdata_gaia:

networks:
  targets_list_network_gaia:
